"""Plural MPP Buyer SDK — Python port of `@plural/mpp-buyer-sdk`.

Automatically intercepts HTTP 402 Payment Required responses, constructs
UPI SBMD credentials, and completes the payment flow.
"""
from .client import (
    PluralBuyer,
    PluralBuyerInstance,
    build_credential,
    decode_challenge,
    decode_receipt,
    encode_credential_header,
    extract_amount_paise,
    validate_challenge,
)
from .config.environments import DEFAULT_BASE_URL, MppEnvironment
from .grantex import (
    AuthorizationCheckResult,
    GrantAuditLogger,
    GrantVerifier,
    MppScopes,
    check_payment_authorization,
    create_audit_pusher,
    extract_per_transaction_limit,
    extract_spending_limit,
    has_scope,
    parse_scope,
)
from .types import (
    Amount,
    Challenge,
    ChallengeRequest,
    CreateMandateOptions,
    CreateTokenOptions,
    Credential,
    CredentialPayload,
    GrantexConfig,
    GrantTokenClaims,
    GrantVerificationResult,
    JwksConfig,
    Mandate,
    MppErrorCode,
    PluralBuyerConfig,
    Receipt,
    SpendingLimit,
    Token,
    TokenDefaults,
)
from .utils.errors import MppChallengeError, MppError, MppNetworkError

__all__ = [
    "Amount",
    "AuthorizationCheckResult",
    "Challenge",
    "ChallengeRequest",
    "CreateMandateOptions",
    "CreateTokenOptions",
    "Credential",
    "CredentialPayload",
    "DEFAULT_BASE_URL",
    "GrantAuditLogger",
    "GrantTokenClaims",
    "GrantVerificationResult",
    "GrantVerifier",
    "GrantexConfig",
    "JwksConfig",
    "Mandate",
    "MppChallengeError",
    "MppEnvironment",
    "MppError",
    "MppErrorCode",
    "MppNetworkError",
    "MppScopes",
    "PluralBuyer",
    "PluralBuyerConfig",
    "PluralBuyerInstance",
    "Receipt",
    "SpendingLimit",
    "Token",
    "TokenDefaults",
    "build_credential",
    "check_payment_authorization",
    "create_audit_pusher",
    "decode_challenge",
    "decode_receipt",
    "encode_credential_header",
    "extract_amount_paise",
    "extract_per_transaction_limit",
    "extract_spending_limit",
    "has_scope",
    "parse_scope",
    "validate_challenge",
]

__version__ = "0.1.0"
